keys:
  - &avalon age18aqpfcqsyx5ak95wjn2udz573lkxmza6k27jeele2vmk9t2gcaqq39jvwa
  - &nico age1y7yxkvc7nqtt0ap3xl796qjenz5lv05vq0sctljexytlwpw2j9vsufxdlj
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *avalon
        - *nico
